#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

sxhkd &
$HOME/.config/polybar/launch.sh

bspc monitor -d 'TERM' 'CODE' 'WEB' 'STUDY' 'READ' 'MUSIC'

bspc config border_width         3
bspc config window_gap           0

bspc config split_ratio          0.6
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		      "#24283b"
bspc config active_border_color	          "#24283b"
bspc config focused_border_color	      "#bb9af7"
bspc config presel_feedback_color	      "#bb9af7"
bspc config urgent_border_color 	      "#f7768e"

